name: BlockFiller
version: 1.0+dev
main: lokiPM\BlockFiller
api: 5.0.0
src-namespace-prefix: lokiPM\BlockFiller

commands:
  blockreplacer:
    description: Fill the selected blocks.
    permission: blockreplacer.fill
    default: op

permissions:
  blockreplacer.fill:
    description: Allows the player to use the /blockreplacer command.
    default: op
